allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: []
apiVersion: security.openshift.io/v1
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
groups: 
kind: SecurityContextConstraints
metadata: 
  annotations: 
    kubernetes.io/description: scc for sas-microanalytic-score service account
  name: sas-microanalytic-score
priority: 0
readOnlyRootFilesystem: true
requiredDropCapabilities:
- ALL
runAsUser:
  type: MustRunAs
  uid: 1001
seLinuxContext: 
  type: RunAsAny
seccompProfiles: 
- runtime/default
supplementalGroups: 
  type: RunAsAny
users: 
volumes: 
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
- nfs