allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities: []
apiVersion: security.openshift.io/v1
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
groups:
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: Open Distro for Elasticsearch SCC
  name: sas-opendistro
priority: 0
readOnlyRootFilesystem: true
requiredDropCapabilities:
- ALL
runAsUser:
  type: RunAsAny
  uid: 1000
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
