apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-model-publish-kaniko
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: "50Gi" #change this to desired capacity
  storageClassName: "odf-encrypted-rwx" # change this the desired storage class
