---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sasfd-runtime-sidecar-scr
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SAS_DETECTION_DEPLOYMENT_NAME
      value: "sas-detection"
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SAS_DETECTION_PROCESSING_DISABLEMESSAGESCHEMATYPEVALIDATION
      value: "true"
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SAS_DETECTION_PROCESSING_DISABLEMETRICS
      value: "false"
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SAS_DETECTION_PROCESSING_REPLYIFTIMEOUT
      value: "true"
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SAS_DETECTION_PROCESSING_SLA
      value: "8500"
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SAS_DETECTION_PROCESSING_EXECUTION_MODE
      value: "SCR"
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SAS_DETECTION_PROCESSING_EXECUTION_URL
      value: http://localhost:8080
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SAS_DETECTION_SERVICE_URL
      value: https://localhost:8777
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SAS_LOG_LEVEL
      value: ERROR
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: PORT
      value: "8777"
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SAS_DETECTION_PROCESSING_OUTPUT_FILTER
      value: "message.sas.system,message.sas.decision,message.request,message.alerted"
  - op: add
    path: /spec/template/spec/containers/0/envFrom/-
    value:
      secretRef:
        name: sas-detection-kafka-secret
  - op: replace
    path: /spec/template/spec/containers/0/ports/0/containerPort
    value: 8777
  - op: add
    path: /spec/template/spec/containers/-
    value:
      name: sas-sda-scr
      image: sas-sda-scr-image
      imagePullPolicy: "IfNotPresent"
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      env:
      - name: SAS_SCR_LOG_LEVEL_App.tk.MAS.Detection.Detect.DS2
        value: DEBUG
      - name: SAS_SCR_LOG_LEVEL_App.tk.Detection
        value: INFO
      - name: PORT
        value: "8080"
      envFrom:
      - configMapRef:
          name: sas-shared-config
      - secretRef:
          name: sas-consul-client
      resources:
        limits:
          cpu: 1000m
          memory: 1000Mi
        requests:
          cpu: 1000m
          memory: 1000Mi
      securityContext:
        runAsUser: 999
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
      volumeMounts:
      - mountPath: /tmp
        name: tmp
target:
  group: apps
  kind: Deployment
  name: sas-detection
  version: v1
---
