SAS_DETECTION_KAFKA_CONSUMER_ENABLED=${kafkaConsumerEnabled}
SAS_DETECTION_KAFKA_ENABLE_HOSTNAME_VERIFICATION=${kafkaHostnameVerify}
SAS_DETECTION_KAFKA_REJECT_TOPIC=${kafkaRejectTopic}
SAS_DETECTION_KAFKA_SECURITY_PROTOCOL=${kafkaSecurityProtocol}
SAS_DETECTION_KAFKA_SERVER=${kafkaHost}:${kafkaPort}
SAS_DETECTION_KAFKA_TDR_TOPIC=${kafkaTdrTopic}
SAS_DETECTION_KAFKA_TOPIC=${kafkaConsumerTopic}
SAS_DETECTION_KAFKA_BYPASS=${kafkaBypass}
SAS_DETECTION_KAFKA_CERTIFICATE_LOCATION=${kafkaCertLocation}
SAS_DETECTION_KAFKA_KEY_LOCATION=${kafkaKeyLocation}
SAS_DETECTION_KAFKA_TRUSTSTORE=${kafkaTrustStoreLocation}
