SAS_DETECTION_KAFKA_CONSUMER_ENABLED={kafka-cons-enable}
SAS_DETECTION_KAFKA_ENABLE_HOSTNAME_VERIFICATION={kafka-host-verify}
SAS_DETECTION_KAFKA_REJECT_TOPIC={reject-topic}
SAS_DETECTION_KAFKA_SECURITY_PROTOCOL={kafka-sec-prot}
SAS_DETECTION_KAFKA_SERVER={kafka-server}
SAS_DETECTION_KAFKA_TDR_TOPIC={tdr-topic}
SAS_DETECTION_KAFKA_TOPIC={input-topic}
SAS_DETECTION_KAFKA_BYPASS={kafka-bypass}
