#SAS-DETECTION
SAS_DETECTION_REDIS_STANDALONE_REDISSERVICEADDRESS=${redisHost}:${redisPort}
SAS_DETECTION_REDIS_HOST=${redisHost}
SAS_DETECTION_REDIS_PORT=${redisPort}
SAS_DETECTION_REDIS_KEY_PREFIX=SASODE|0
SAS_DETECTION_REDIS_POOL_SIZE=10
SAS_DETECTION_REDIS_TLS_ENABLED=${redisTlsEnabled}
SAS_DETECTION_REDIS_SERVER_DOMAIN=${redisServerDomain}
#SCR
SAS_REDIS_HOST=${redisHost}
SAS_REDIS_PORT=${redisPort}
SAS_REDIS_KEY_PREFIX=SASODE|0
SAS_REDIS_PROFILE_COMPRESS=${redisProfileCompress}
SAS_REDIS_TLS=${redisTlsScr}
SAS_REDIS_SERVER_DOMAIN=${redisServerDomain}
SAS_REDIS_CA_CERT=/security/trustedcerts.pem
