#SAS-DETECTION
SAS_DETECTION_REDIS_STANDALONE_REDISSERVICEADDRESS={redis-host}:{redis-port}
SAS_DETECTION_REDIS_HOST={redis-host}
SAS_DETECTION_REDIS_PORT={redis-port}
SAS_DETECTION_REDIS_KEY_PREFIX="SASODE|0"
SAS_DETECTION_REDIS_POOL_SIZE="10"
SAS_DETECTION_REDIS_TLS_ENABLED={redis-tls-enabled}
SAS_DETECTION_REDIS_SERVER_DOMAIN={redis-server-domain}
#SCR
SAS_REDIS_HOST={redis-host}
SAS_REDIS_PORT={redis-port}
SAS_REDIS_KEY_PREFIX="SASODE|0"
SAS_REDIS_PROFILE_COMPRESS=false
SAS_REDIS_TLS={redis-tls-scr} ## Setting to 0, N, or F will prohibit TLS. Setting to 1, Y, or T will allow TLS.
SAS_REDIS_SERVER_DOMAIN={redis-server-domain}
