### The following Roles and RoleBindings give your detection deployments
### permissions required to retrieve metrics and restart their pods
### Only the NAMESPACE must be specified
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reader
  namespace: {{ NAMESPACE }}
rules:
  - apiGroups: [""]
    resources: ["deployments", "deployments/scale", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale", "pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scaler
  namespace: {{ NAMESPACE }}
rules:
  - apiGroups: [""]
    resources: ["deployments", "deployments/scale"]
    verbs: ["update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secretReader
  namespace: {{ NAMESPACE }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader-role-binding-default
  namespace: {{ NAMESPACE }}
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scaler-role-binding-default
  namespace: {{ NAMESPACE }}
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: scaler
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secretReader-role-binding-default
  namespace: {{ NAMESPACE }}
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: secretReader
  apiGroup: rbac.authorization.k8s.io