apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

transformers:
- sas-detection-patch.yaml

configMapGenerator:
- name: sas-detection-datastore-config
  envs:
    - redis-config.yaml
    - kafka-config.yaml
    - sas-detection-config.yaml

secretGenerator:
- name: sas-detection-datastore-secrets
  envs:
  - redis-secret.yaml
  - kafka-secret.yaml
