SAS_DETECTION_DEPLOYMENT_NAME=sas-detection
PORT=8777
SAS_LOG_LEVEL=INFO
SAS_DETECTION_REDIS_TLS_CACERT=/customer-provided-ca-certificates
SAS_DETECTION_KAFKA_SSL_TRUSTSTORE=/customer-provided-ca-certificates
SAS_DETECTION_PROCESSING_DISABLEMETRICS=false
SAS_DETECTION_PROCESSING_EXECUTION_URL=http://localhost:8080
SAS_DETECTION_PROCESSING_OUTPUT_FILTER=message.sas.system,message.sas.decision,message.request,message.alerted
SAS_DETECTION_PROCESSING_SETVERBOSE=1
SAS_DETECTION_PROCESSING_SLA=850
SAS_DETECTION_SERVICE_URL=http://localhost:8777
SAS_DETECTION_WATCHER_INTERVAL_SEC=120
SAS_DETECTION_WATCHER_SSL_ENABLED=true
SAS_DETECTION_PROCESSING_REPLYIFTIMEOUT=true
