apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-consul-storage-class-transformer
patch: |-
  - op: add
    path: /spec/volumeClaimTemplates/0/spec/storageClassName
    value: {{ STORAGE-CLASS }}
target:
  kind: StatefulSet
  name: sas-consul-server
