---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-image-pull-secret-transformer-deployment
patch: |-
  - op: replace
    path: /spec/template/spec/imagePullSecrets/0/name
    value: ${imagePullSecret}
target:
  kind: Deployment
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-image-pull-secret-transformer-daemonset
patch: |-
  - op: replace
    path: /spec/template/spec/imagePullSecrets/0/name
    value: ${imagePullSecret}
target:
  kind: DaemonSet
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-image-pull-secret-transformer-statefulset
patch: |-
  - op: replace
    path: /spec/template/spec/imagePullSecrets/0/name
    value: ${imagePullSecret}
target:
  kind: StatefulSet
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-image-pull-secret-transformer-job
patch: |-
  - op: replace
    path: /spec/template/spec/imagePullSecrets/0/name
    value: ${imagePullSecret}
target:
  kind: Job
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-image-pull-secret-transformer-cronjob
patch: |-
  - op: replace
    path: /spec/jobTemplate/spec/template/spec/imagePullSecrets/0/name
    value: ${imagePullSecret}
target:
  kind: CronJob
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-image-pull-secret-transformer-postgres
patch: |-
  - op: replace
    path: /spec/imagePullSecrets/0/name
    value: ${imagePullSecret}
target:
  kind: PostgresCluster
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-image-pull-secret-transformer-casdeployment
patch: |-
  - op: replace
    path: /spec/controllerTemplate/spec/imagePullSecrets/0/name
    value: ${imagePullSecret}
target:
  kind: CASDeployment
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-image-pull-secret-transformer-podtemplate
patch: |-
  - op: replace
    path: /template/spec/imagePullSecrets/0/name
    value: ${imagePullSecret}
target:
  kind: PodTemplate
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-image-pull-secret-transformer-opendistrocluster
patch: |-
  - op: replace
    path: /spec/template/spec/imagePullSecrets/0/name
    value: ${imagePullSecret}
target:
  kind: OpenDistroCluster
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-image-pull-secret-transformer-prepull
patch: |-
  - op: replace
    path: /imagePullSecrets/0/name
    value: ${imagePullSecret}
target:
  version: v1
  kind: ServiceAccount
  name: sas-prepull
---